[2024-09-22T15:14:09.525+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T15:14:09.953+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NY_TAXI.download_data scheduled__2021-01-17T00:00:00+00:00 [queued]>
[2024-09-22T15:14:10.172+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NY_TAXI.download_data scheduled__2021-01-17T00:00:00+00:00 [queued]>
[2024-09-22T15:14:10.174+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-22T15:14:10.969+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): download_data> on 2021-01-17 00:00:00+00:00
[2024-09-22T15:14:11.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'NY_TAXI', 'download_data', 'scheduled__2021-01-17T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/download.py', '--cfg-path', '/tmp/tmpk694i8qc']
[2024-09-22T15:14:11.065+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask download_data
[2024-09-22T15:14:11.207+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-22T15:14:11.213+0000] {standard_task_runner.py:72} INFO - Started process 358 to run task
[2024-09-22T15:14:20.916+0000] {task_command.py:467} INFO - Running <TaskInstance: NY_TAXI.download_data scheduled__2021-01-17T00:00:00+00:00 [running]> on host 8c9160901df5
[2024-09-22T15:14:23.041+0000] {job.py:229} INFO - Heartbeat recovered after 13.77 seconds
[2024-09-22T15:14:33.792+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NY_TAXI' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-17T00:00:00+00:00'
[2024-09-22T15:14:33.796+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T15:14:33.882+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T15:14:33.883+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo 2021-01-17']
[2024-09-22T15:14:33.930+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T15:14:34.005+0000] {subprocess.py:93} INFO - 2021-01-17
[2024-09-22T15:14:34.006+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-22T15:14:34.516+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T15:14:34.527+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=NY_TAXI, task_id=download_data, run_id=scheduled__2021-01-17T00:00:00+00:00, execution_date=20210117T000000, start_date=20240922T151409, end_date=20240922T151434
[2024-09-22T15:14:35.210+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T15:14:35.343+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T15:14:35.734+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-22T15:14:36.045+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
